# Generated by Django 3.2.7 on 2021-09-03 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Номеклатура')),
                ('type', models.IntegerField(default=0, verbose_name='Тип')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='nsiIkul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код ИКЮЛ')),
                ('name', models.CharField(max_length=255, verbose_name='Наименвоание вида юридического лица')),
            ],
            options={
                'verbose_name': 'ИКЮЛ',
                'verbose_name_plural': 'ИКЮЛ',
            },
        ),
        migrations.CreateModel(
            name='nsiOkato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11, unique=True, verbose_name='Код ОКАТО')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование по ОКАТО')),
                ('parent', models.CharField(max_length=11, null=True)),
            ],
            options={
                'verbose_name': 'ОКАТО',
                'verbose_name_plural': 'ОКАТО',
            },
        ),
        migrations.CreateModel(
            name='nsiOkei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код ОКЕИ')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование по ОКЕИ')),
                ('symbol', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'ОКЕИ',
                'verbose_name_plural': 'ОКЕИ',
            },
        ),
        migrations.CreateModel(
            name='nsiOkeiGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Код группы')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование группы')),
            ],
        ),
        migrations.CreateModel(
            name='nsiOkeiSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код раздела')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование раздела')),
            ],
        ),
        migrations.CreateModel(
            name='nsiOkfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код ОКФС')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование по ОКФС')),
            ],
            options={
                'verbose_name': 'ОКФС',
                'verbose_name_plural': 'ОКФС',
            },
        ),
        migrations.CreateModel(
            name='nsiOkogu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True, verbose_name='Код ОКОГУ')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование по ОКОГУ')),
                ('parent', models.CharField(max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'ОКОГУ',
                'verbose_name_plural': 'ОКОГУ',
            },
        ),
        migrations.CreateModel(
            name='nsiOkopf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код ОКОПФ')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование по ОКОГУ')),
                ('parent', models.CharField(max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'ОКОПФ',
                'verbose_name_plural': 'ОКОПФ',
            },
        ),
        migrations.CreateModel(
            name='nsiOkpd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Код ОКПД')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование по ОКПД')),
                ('parent', models.CharField(max_length=8, null=True)),
                ('section', models.CharField(max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'ОКПД',
                'verbose_name_plural': 'ОКПД',
            },
        ),
        migrations.CreateModel(
            name='nsiOkpd2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Код ОКПД2')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование по ОКПД2')),
                ('parent', models.CharField(max_length=8, null=True)),
            ],
            options={
                'verbose_name': 'ОКПД2',
                'verbose_name_plural': 'ОКПД2',
            },
        ),
        migrations.CreateModel(
            name='nsiOkpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код ОКПО')),
                ('name', models.CharField(max_length=500, null=True, verbose_name='Наименование ОКПО')),
            ],
            options={
                'verbose_name': 'ОКПО',
                'verbose_name_plural': 'ОКПО',
            },
        ),
        migrations.CreateModel(
            name='nsiOktmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11, unique=True, verbose_name='Код ОКФС')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование по ОКФС')),
                ('parent', models.CharField(max_length=11, null=True)),
            ],
            options={
                'verbose_name': 'ОКТМО',
                'verbose_name_plural': 'ОКТМО',
            },
        ),
        migrations.CreateModel(
            name='nsiOkv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код валюты')),
                ('digitalCode', models.CharField(max_length=100, verbose_name='Цифровой код валюты')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование валюты')),
                ('shortName', models.CharField(max_length=500, null=True, verbose_name='Наименование валюты')),
            ],
            options={
                'verbose_name': 'ОК валют',
                'verbose_name_plural': 'ОК валют',
            },
        ),
        migrations.CreateModel(
            name='nsiOkved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='Код ОКВЕД')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование по ОКВЕД')),
                ('parent', models.CharField(max_length=15, null=True)),
                ('section', models.CharField(max_length=1, verbose_name='Раздел')),
                ('subsection', models.CharField(max_length=2, null=True, verbose_name='Подраздел')),
            ],
            options={
                'verbose_name': 'ОКВЭД',
                'verbose_name_plural': 'ОКВЭД',
            },
        ),
        migrations.CreateModel(
            name='nsiOkved2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, verbose_name='Код ОКВЕД2')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование по ОКВЕД2')),
                ('parent', models.CharField(max_length=15, null=True)),
                ('section', models.CharField(max_length=1, verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'ОКВЭД2',
                'verbose_name_plural': 'ОКВЭД2',
            },
        ),
        migrations.CreateModel(
            name='nsiPPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11, unique=True, verbose_name='Код ППО')),
                ('name', models.CharField(max_length=2000, verbose_name='Наименование ППО')),
            ],
            options={
                'verbose_name': 'ППО',
                'verbose_name_plural': 'ППО',
            },
        ),
        migrations.CreateModel(
            name='nsiTimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.IntegerField(default=0, verbose_name='Смещение отностельно MSK')),
                ('name', models.CharField(max_length=100, verbose_name='Название временной зоны')),
            ],
            options={
                'verbose_name': 'Временная зона',
                'verbose_name_plural': 'Временные зоны',
            },
        ),
        migrations.CreateModel(
            name='nsiTypeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тип контакта')),
            ],
            options={
                'verbose_name': 'Тип контакта',
                'verbose_name_plural': 'Типы контактов',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_org', models.CharField(choices=[('L', 'Юридическое лицо'), ('P', 'Физическое лицо')], default='L', max_length=1, verbose_name='Тип органзиации')),
                ('full_name', models.CharField(max_length=300, verbose_name='Полное имя')),
                ('short_name', models.CharField(max_length=100, verbose_name='Сокращенное наименвоание')),
                ('registration_date', models.DateTimeField(null=True, verbose_name='Дата постановки на учет')),
                ('ogrn', models.CharField(max_length=13, verbose_name='ОГРН')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('legalAddress', models.TextField(max_length=2000, null=True, verbose_name='Юридический адрес')),
                ('postalAddress', models.TextField(max_length=2000, null=True, verbose_name='Почтовый адрес')),
                ('okato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_nsiOkato', to='main_app.nsiokato', verbose_name='ОКАТО')),
                ('okfs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_okfs', to='main_app.nsiokfs', verbose_name='ОКФС')),
                ('okopf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_okopf', to='main_app.nsiokopf', verbose_name='ОКОПФ')),
                ('okpo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_okpo', to='main_app.nsiokpo', verbose_name='ОКПО')),
                ('oktmo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_oktmo', to='main_app.nsioktmo', verbose_name='ОКТМО')),
                ('timeZone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_timeZone', to='main_app.nsitimezone', verbose_name='Временная зона')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=300, null=True, verbose_name='Имя')),
                ('middleName', models.CharField(max_length=300, null=True, verbose_name='Отчество')),
                ('lastName', models.CharField(max_length=300, null=True, verbose_name='Фамилия')),
                ('inn', models.CharField(max_length=12, null=True, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Физические лица',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('link_to_doc', models.URLField(verbose_name='Ссылка на документацию')),
                ('okpd2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query', to='main_app.nsiokpd2', verbose_name='ОКПД2')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query', to='main_app.organization', verbose_name='ОКПД2')),
            ],
        ),
        migrations.CreateModel(
            name='QueryNomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0.0, verbose_name='Количество')),
                ('ei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_nomenclature', to='main_app.nsiokei', verbose_name='Единица измерения')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_nomenclature', to='main_app.nomenclature', verbose_name='Номенклатура')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_nomenclature', to='main_app.query', verbose_name='Запрос')),
            ],
        ),
        migrations.CreateModel(
            name='PersonContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.person', verbose_name='Физическое лицо')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsitypecontact', verbose_name='Тип контакта')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationOkved2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMain', models.BooleanField(default=False, verbose_name='Основной')),
                ('okved2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokved2', verbose_name='ОКВЭД2')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.organization', verbose_name='Организация')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationOkved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMain', models.BooleanField(default=False, verbose_name='Основной')),
                ('okved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokved', verbose_name='ОКВЭД')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.organization', verbose_name='Организация')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.organization', verbose_name='Организация')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_contact', to='main_app.person', verbose_name='Физическое лицо')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsitypecontact', verbose_name='Тип контакта')),
            ],
        ),
        migrations.AddField(
            model_name='nsiokei',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokeigroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='nsiokei',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokeisection', verbose_name='Раздел'),
        ),
    ]
