# Generated by Django 3.2.7 on 2021-09-04 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210904_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsiokpd2',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код ОКПД2'),
        ),
        migrations.AlterField(
            model_name='query',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query', to='main_app.organization', verbose_name='Организатор'),
        ),
    ]
