# Generated by Django 3.2.7 on 2021-09-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210904_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(default=1, max_length=12, unique=True, verbose_name='ИНН'),
            preserve_default=False,
        ),
    ]
