# Generated by Django 3.2.7 on 2021-09-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_organization_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(max_length=12, verbose_name='ИНН'),
        ),
    ]
