# Generated by Django 3.2.7 on 2021-09-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210904_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsiokei',
            name='code',
            field=models.CharField(max_length=5, verbose_name='Код ОКЕИ'),
        ),
    ]
