# Generated by Django 3.2.7 on 2021-09-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_nsiokei_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='descritption',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='query',
            name='num',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер запроса'),
        ),
    ]
