# Generated by Django 3.2.7 on 2021-09-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210904_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='descritption',
            new_name='description',
        ),
    ]
