# Generated by Django 3.2.7 on 2021-09-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210904_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Детальная информация'),
        ),
    ]
