# Generated by Django 3.2.7 on 2021-09-04 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20210905_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nsiokpd2',
            name='parent',
        ),
    ]
