# Generated by Django 3.2.7 on 2021-09-05 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_nsiokpd2_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nsiokei',
            options={'ordering': ['code'], 'verbose_name': 'ОКЕИ', 'verbose_name_plural': 'ОКЕИ'},
        ),
        migrations.AlterModelOptions(
            name='nsiokpd2',
            options={'ordering': ['code'], 'verbose_name': 'ОКПД2', 'verbose_name_plural': 'ОКПД2'},
        ),
        migrations.AlterModelOptions(
            name='nsiokved2',
            options={'ordering': ['code'], 'verbose_name': 'ОКВЭД2', 'verbose_name_plural': 'ОКВЭД2'},
        ),
        migrations.AlterModelOptions(
            name='organizationokved2',
            options={'ordering': ['okved2']},
        ),
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ['okpd2'], 'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AlterField(
            model_name='organizationokved2',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_okved', to='main_app.organization', verbose_name='Организация'),
        ),
    ]
