# Generated by Django 3.2.7 on 2021-09-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20210905_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='defend',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ответчик (выиграл/проиграл/прочее)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='director',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='organization',
            name='info',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Краткая информация'),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Истец (выиграл/проиграл/прочее)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tender',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Торги (учавствовал/выиграл/госконтракт)'),
        ),
    ]
