# Generated by Django 3.2.7 on 2021-09-05 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20210905_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuerySupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_supplier', to='main_app.query', verbose_name='Запрос')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_supplier', to='main_app.organization', verbose_name='Поставщик')),
            ],
        ),
    ]
