# Generated by Django 3.2.7 on 2021-09-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_querysupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='querysupplier',
            name='status',
            field=models.CharField(default='', max_length=200, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
